name: Release

on:
  release:
    types:
      - published

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_USER_PAT }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@drashland'
      - name: Install deps
        run: yarn install
      - name: Build & Publish
        run: |
          yarn build
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_USER_PAT }}
      # Setup .npmrc file to publish to github
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@drashland'
      - name: Install deps
        run: yarn install
      - name: Build & Publish
        run: |
          yarn build
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-egg:
    runs-on: ubuntu-latest
    steps:
      - name: Notify the castle about this release
        run: |
          curl -X POST \
            -u "${{ secrets.CI_USER_NAME }}:${{ secrets.CI_USER_PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            --data '{"event_type": "release", "client_payload": { "repo": "moogle", "module": "moogle", "version": "${{ github.ref }}" }}' \
            https://api.github.com/repos/drashland/castle/dispatches

